kalwalt/gatsby-starter-i18n-bulma

gatsby-config.js, src/components/Layout.js, src/data/articleTree.js, src/pages/about.en.md, src/pages/artworks/artworks-page-test.en.md, src/pages/artworks/index.en.md, src/pages/blog/2019-02-01-mio-primo-blog-post-gatsby.it.md, src/pages/blog/2019-02-01-my-first-gatsby-blog-post.en.md, src/pages/blog/2019-03-11-news-from-art-planet.en.md, src/pages/blog/2019-03-11-notizie-dal-pianeta-arte.it.md, src/pages/contact.en.md, src/pages/contatto.it.md, src/pages/index.en.md, src/pages/index.it.md, src/pages/opere/index.it.md, src/pages/opere/pagina-artworks-test.it.md, src/pages/presentazione.it.md
This PR try to solve the issue with ids (from frontmatter) of the pages. The issue came from the fact that ids was declared in some pages as string values ( with `allJavascriptFrontmatter` plugin) and all the other as numeric values: i changed that as strings and solved that issue.
=> 90% solved issue, only a problem with index blog page and about page

src/components/Footer.js
Very simple PR adding a `FormattedMessage` component to every menu label.
=> added FormattedMessage to every menu link

src/data/messages/en.js, src/data/messages/it.js, src/pages/404.js
Added the 404 page, it switch different messages based on the langs.
=> 404 page feature

src/pages/tags.js, src/templates/artworks.js, src/templates/home.js, src/templates/tags.js
I try to fix the https://github.com/kalwalt/gatsby-starter-i18n-bulma/issues/18 issue: Basically because some html tags and div containers are without CSS className styling.
=> Titles fixing

gatsby-config.js, src/components/Layout.js, src/components/SEO/SEO.js, src/components/SEO/SchemaOrg.js, src/pages/blog/index.en.js, src/pages/blog/index.it.js, src/templates/blog-post.js
Discussion started here: https://github.com/kalwalt/gatsby-starter-i18n-bulma/issues/10
=> Seo component for blog-posts and basic site metadata in Layout

src/img/logo.svg, src/pages/blog/index.en.js, src/pages/blog/index.it.js, src/pages/index.en.md, src/pages/index.it.md, src/pages/opere/scultura.it.md
Simply adding some images and a new logo. I decided to change the name of the logo from KALDI to KAKI like the fruit Persimmon (similar to the italian language). I think that is funny even if this template will become my future website. All the images are taken from wikipedia. I will leave a comment in the code for this.
=> Adding images

src/components/Layout.js, src/components/Main.js, src/templates/artworks.js, src/templates/blog-post.js, src/templates/contacts.js, src/templates/home.js, src/templates/tags.js
This PR add a `<main>` html component to the Layout. This will be added to all the templates.
=> added Main component

src/components/Footer.js, src/components/Layout.js, src/components/all.sass
Including the whole` Fontawesome` lib make too big the build file. I decided to use instead also in the footer the `react-icons` package. I can't stack the icons as before, but i prefer this approach for the reason explained above.
=> Fontawesome icons dev

.gitignore, yarn.lock
=> adding yarn.lock see https://yarnpkg.com/lang/en/docs/yarn-lock/

src/components/Layout.js
I am trying to simplify the code, and to remove the parts that are not necessary anymore.
=> improvement in the code but not yet simplyfied

src/data/articleTree.js, src/pages/contact/thanks.en.md, src/pages/contatto/grazie.it.md, src/templates/contacts.js, src/templates/message.js
This PR try to implement the features discussed in https://github.com/kalwalt/gatsby-starter-i18n-bulma/issues/49
=> Contact form improves

package.json, src/components/Lightbox.js, src/pages/artworks/artworks-page-test.en.md, src/pages/artworks/index.en.md, src/pages/artworks/interactivity.en.md, src/pages/artworks/painting.en.md, src/pages/artworks/performance.en.md, src/pages/artworks/sculpture.en.md, src/pages/opere/arte-interattiva.it.md, src/pages/opere/index.it.md, src/pages/opere/pagina-artworks-test.it.md, src/pages/opere/performance.it.md, src/pages/opere/pittura.it.md, src/pages/opere/scultura.it.md, src/templates/artworks.js, yarn.lock
I started form this example starter https://github.com/416serg/gatsby-starter-lightbox to implement a simple gallery with lightbox modal.
As a reference it is useful the tutorial: https://416serg.me/building-a-custom-accessible-image-lightbox-in-gatsbyjs/
Demo here: https://gatsby-lightbox.416serg.me/
=> Image feature - new Lightbox component

src/templates/contacts.js
This is only a small fix, i missed  a div with the action variable inside, it was only for testing pourposes...
=> deleting the action <div> log

package.json, src/components/all.sass, src/templates/artworks.js, src/templates/home.js, yarn.lock
A simple PR to add the animate.css library into the project. I can import the .css version but not the .sass version, don't know why...
=> added animate.css and a simple animation to some titles

src/components/Copyright.js, src/components/DropDownMenu.js, src/components/Footer.js, src/components/Header.js, src/components/Lightbox.js, src/components/SelectLanguage.js, src/components/Slider.js, src/components/all.sass, src/data/articleTree.js, src/data/artworksMenu.js, src/data/messages/en.js, src/data/messages/it.js, src/pages/artworks/introduction.en.md, src/pages/opere/introduzione.it.md, src/pages/tags.js, src/templates/artworks.js, src/templates/blog-post.js, src/templates/contacts.js, src/templates/home.js, src/templates/message.js, src/templates/tags.js
I am trying to improve the css styling of the template.
=> Styling improvements

static/admin/config.yml
The extension should add the finale prefix language.
=> trying the extension mechanism

src/components/ContactDetails.js, src/components/Footer.js, src/components/Header.js, src/components/ScrollToTop.js, src/components/all.sass, src/pages/contact.en.md, src/pages/contatto.it.md, src/templates/contacts.js
=> Contact form improves and last changes before first release

src/components/Layout.js, src/components/SEO/SEO.js, src/templates/about.js, src/templates/artworks-intro.js, src/templates/artworks-portfolio.js, src/templates/artworks-simple.js, src/templates/artworks.js, src/templates/blog-post.js, src/templates/contacts.js, src/templates/home.js
Missed to add SEO Component to most of templates, i didn't add to tags templates, i think it's not necessary but i will think about.
=> Fix seo component

src/components/TagList.js, src/data/messages/en.js, src/data/messages/it.js, src/templates/about.js, src/templates/allTags.js, src/templates/artworks-intro.js, src/templates/artworks-portfolio.js, src/templates/artworks-simple.js, src/templates/artworks.js, src/templates/blog-post.js, src/templates/home.js, src/templates/tags.js
from this PR https://github.com/kalwalt/www.walterperdan.com/pull/2
=> Improved tags system

package.json, src/components/AccordionCollaps.js, src/components/Header.js, src/components/RootMenuMobile.js, src/components/all.sass
Testing the new creative-bulma v.1.0.3 - thanks to @CreativeBulma - on a Mobile menu with accordions. A rivisited version of the code 
of this PR https://github.com/kalwalt/gatsby-starter-i18n-bulma/pull/93
Read the comments in the code for more details.
The code is compiled fine in both development and build phase.
=> Testing creative bulma

package.json, yarn.lock
maintenance release before upgrading some Components.
Removed:
- bootstrap
- react-typography
- typography
- typography-breakpoint-constants
=> Removing not necessary packages

src/components/Layout.js
This PR will fix issue #141
The code check if the id is equal to zero (the home page) and don't add an extra `/` at the end of the path.
I removed some not used params in the **startPath** and **check_path** functions to avoid mistakes.
=> better langs menu 
